#!/bin/bash

# This script runs 3dClustSim for each model using acf parameters generated by calculate_group_average.R

module load R
Rscript calculate_group_average.R $MODEL $FXMODELDIR $OUTPUTDIR $SUBLIST

module load afni

PARAMS=`cat "$OUTPUTDIR/${MODEL}"_ACFparameters_group_average.txt`

echo "running $MODEL"
echo "${RXMODELDIR}"/"${MODEL}"
3dClustSim -mask "${RXMODELDIR}"/"${MODEL}"+tlrc[0] -acf `echo "${PARAMS}"` > "${OUTPUTDIR}"/3dClustStim_"${MODEL}".txt
